#! /usr/bin/env bash

# Setup script for devpod

export XDG_CONFIG_HOME="$HOME"/.config

ln -sf $HOME/dotfiles/.cargo .cargo
ln -sf $HOME/dotfiles/.config .config
ln -sf $HOME/dotfiles/.terminfo .terminfo
ln -sf $HOME/dotfiles/.zshrc .zshrc
ln -sf $HOME/dotfiles/.zfunc .zfunc
ln -sf $HOME/dotfiles/.zprofile .zprofile
ln -sf $HOME/dotfiles/.zshenv .zshenshenv
