# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  editPreset: "nvim-remote"

git:
  paging:
    pager: bat --paging=never --style=plain
    externalDiffCommand: "difft --color=always"
